# Generated by Django 3.1.12 on 2024-12-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritecity',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
    ]
